import type { IconType } from "react-icons";
import { FiCode } from "react-icons/fi";
import {
  SiAngular,
  SiAstro,
  SiBootstrap,
  SiCss,
  SiCplusplus,
  SiCypress,
  SiDjango,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiFlask,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGraphql,
  SiHtml5,
  SiInsomnia,
  SiJavascript,
  SiJenkins,
  SiJest,
  SiKotlin,
  SiLaravel,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNetlify,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiOpenjdk,
  SiPhp,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiRabbitmq,
  SiReact,
  SiRedis,
  SiRust,
  SiSass,
  SiSpringboot,
  SiSqlite,
  SiSupabase,
  SiSvelte,
  SiSwagger,
  SiTailwindcss,
  SiTerraform,
  SiTypescript,
  SiVercel,
  SiVite,
  SiVitest,
  SiVuedotjs,
} from "react-icons/si";
import { TbApi } from "react-icons/tb";

type TechIconConfig = {
  icon: IconType;
  iconClassName: string;
};

const techIcons: Record<string, TechIconConfig> = {
  React: { icon: SiReact, iconClassName: "text-[#61DAFB]" },
  "React.js": { icon: SiReact, iconClassName: "text-[#61DAFB]" },
  TS: { icon: SiTypescript, iconClassName: "text-[#3178C6]" },
  TypeScript: { icon: SiTypescript, iconClassName: "text-[#3178C6]" },
  JS: { icon: SiJavascript, iconClassName: "text-[#F7DF1E]" },
  JavaScript: { icon: SiJavascript, iconClassName: "text-[#F7DF1E]" },
  HTML: { icon: SiHtml5, iconClassName: "text-[#E34F26]" },
  CSS: { icon: SiCss, iconClassName: "text-[#1572B6]" },
  Sass: { icon: SiSass, iconClassName: "text-[#CC6699]" },
  SCSS: { icon: SiSass, iconClassName: "text-[#CC6699]" },
  Tailwind: { icon: SiTailwindcss, iconClassName: "text-[#06B6D4]" },
  TailwindCSS: { icon: SiTailwindcss, iconClassName: "text-[#06B6D4]" },
  Bootstrap: { icon: SiBootstrap, iconClassName: "text-[#7952B3]" },
  Vite: { icon: SiVite, iconClassName: "text-[#646CFF]" },
  Next: { icon: SiNextdotjs, iconClassName: "text-white" },
  "Next.js": { icon: SiNextdotjs, iconClassName: "text-white" },
  Angular: { icon: SiAngular, iconClassName: "text-[#DD0031]" },
  Vue: { icon: SiVuedotjs, iconClassName: "text-[#4FC08D]" },
  Svelte: { icon: SiSvelte, iconClassName: "text-[#FF3E00]" },
  Astro: { icon: SiAstro, iconClassName: "text-[#FF5D01]" },
  Node: { icon: SiNodedotjs, iconClassName: "text-[#5FA04E]" },
  "Node.js": { icon: SiNodedotjs, iconClassName: "text-[#5FA04E]" },
  EX: { icon: SiExpress, iconClassName: "text-[#E5E7EB]" },
  Express: { icon: SiExpress, iconClassName: "text-[#E5E7EB]" },
  "Express.js": { icon: SiExpress, iconClassName: "text-[#E5E7EB]" },
  Nest: { icon: SiNestjs, iconClassName: "text-[#E0234E]" },
  NestJS: { icon: SiNestjs, iconClassName: "text-[#E0234E]" },
  API: { icon: TbApi, iconClassName: "text-[#F59E0B]" },
  REST: { icon: TbApi, iconClassName: "text-[#F59E0B]" },
  GraphQL: { icon: SiGraphql, iconClassName: "text-[#E10098]" },
  Swagger: { icon: SiSwagger, iconClassName: "text-[#85EA2D]" },
  Prisma: { icon: SiPrisma, iconClassName: "text-[#64B4C3]" },
  PG: { icon: SiPostgresql, iconClassName: "text-[#4169E1]" },
  PostgreSQL: { icon: SiPostgresql, iconClassName: "text-[#4169E1]" },
  Postgres: { icon: SiPostgresql, iconClassName: "text-[#4169E1]" },
  MySQL: { icon: SiMysql, iconClassName: "text-[#4479A1]" },
  MongoDB: { icon: SiMongodb, iconClassName: "text-[#47A248]" },
  SQLite: { icon: SiSqlite, iconClassName: "text-[#003B57]" },
  Firebase: { icon: SiFirebase, iconClassName: "text-[#FFCA28]" },
  Supabase: { icon: SiSupabase, iconClassName: "text-[#3ECF8E]" },
  Redis: { icon: SiRedis, iconClassName: "text-[#DC382D]" },
  RabbitMQ: { icon: SiRabbitmq, iconClassName: "text-[#FF6600]" },
  Python: { icon: SiPython, iconClassName: "text-[#3776AB]" },
  Java: { icon: SiOpenjdk, iconClassName: "text-[#ED8B00]" },
  "C++": { icon: SiCplusplus, iconClassName: "text-[#00599C]" },
  PHP: { icon: SiPhp, iconClassName: "text-[#777BB4]" },
  Kotlin: { icon: SiKotlin, iconClassName: "text-[#7F52FF]" },
  Rust: { icon: SiRust, iconClassName: "text-[#CE422B]" },
  Git: { icon: SiGit, iconClassName: "text-[#F05032]" },
  GitHub: { icon: SiGithub, iconClassName: "text-white" },
  GitLab: { icon: SiGitlab, iconClassName: "text-[#FC6D26]" },
  Docker: { icon: SiDocker, iconClassName: "text-[#2496ED]" },
  Linux: { icon: SiLinux, iconClassName: "text-[#FCC624]" },
  Nginx: { icon: SiNginx, iconClassName: "text-[#009639]" },
  Jenkins: { icon: SiJenkins, iconClassName: "text-[#D24939]" },
  Terraform: { icon: SiTerraform, iconClassName: "text-[#7B42BC]" },
  Vercel: { icon: SiVercel, iconClassName: "text-white" },
  Netlify: { icon: SiNetlify, iconClassName: "text-[#00C7B7]" },
  Jest: { icon: SiJest, iconClassName: "text-[#C21325]" },
  Vitest: { icon: SiVitest, iconClassName: "text-[#6E9F18]" },
  Cypress: { icon: SiCypress, iconClassName: "text-[#69D3A7]" },
  Postman: { icon: SiPostman, iconClassName: "text-[#FF6C37]" },
  Insomnia: { icon: SiInsomnia, iconClassName: "text-[#5849BE]" },
  Figma: { icon: SiFigma, iconClassName: "text-[#F24E1E]" },
  Django: { icon: SiDjango, iconClassName: "text-[#44B78B]" },
  Flask: { icon: SiFlask, iconClassName: "text-white" },
  Laravel: { icon: SiLaravel, iconClassName: "text-[#FF2D20]" },
  Spring: { icon: SiSpringboot, iconClassName: "text-[#6DB33F]" },
};

export function getProjectTechIcon(tech: string): TechIconConfig {
  return techIcons[tech] ?? { icon: FiCode, iconClassName: "text-arcade-yellow" };
}
